C0=zeros(n,6);
C=zeros(n,6);
A=zeros(n,6);
B=zeros(n,6);
D=zeros(n,6);
F=zeros(n,6);
alpha=zeros(n,6);
beta=zeros(n,6);
x=linspace(0,1,n);
VV=zeros(nt,1); %arrays for future storage of data and plotting
XXs=zeros(nt,1);
RRd=zeros(nt,1);
tt=zeros(nt,1);
UU=zeros(nt,1);% array for undersaturation from first to last distance lenghth point 
Tsave=zeros(nt,1);
ZrPls=zeros(nt,1);
Xp_sav=zeros(nt,1);
CC=zeros(nt,n,6);